### 测试numpy安装成功

In [35]:
from numpy import *

In [36]:
a = random.rand(4,4)

In [37]:
print(a)

[[ 0.11540114  0.57388744  0.64615162  0.04558949]
 [ 0.25413864  0.51970238  0.62965259  0.99353374]
 [ 0.40252924  0.33923054  0.94808533  0.38230899]
 [ 0.97683401  0.28889942  0.30229978  0.39109444]]


### Numpy函数库中存在2种数据类型，矩阵matrix 和 数组array

### mat（）函数可将数组转为矩阵

In [38]:
b = mat(a)

In [39]:
print(b)

[[ 0.11540114  0.57388744  0.64615162  0.04558949]
 [ 0.25413864  0.51970238  0.62965259  0.99353374]
 [ 0.40252924  0.33923054  0.94808533  0.38230899]
 [ 0.97683401  0.28889942  0.30229978  0.39109444]]


### .I操作符实现矩阵的求逆运算

In [41]:
c = b.I

In [42]:
print(c)

[[-0.19496971 -0.46966516  0.08298058  1.13474518]
 [ 2.26093884  0.50014997 -2.01058765  0.4312892 ]
 [-0.36189221 -0.44108843  1.77769031 -0.57503315]
 [-0.90344149  1.14456446 -0.0961303  -0.15143272]]


In [43]:
a*c

matrix([[  1.00000000e+00,   0.00000000e+00,   2.22044605e-16,
           0.00000000e+00],
        [  5.55111512e-17,   1.00000000e+00,   0.00000000e+00,
          -9.71445147e-17],
        [  1.11022302e-16,   0.00000000e+00,   1.00000000e+00,
           8.32667268e-17],
        [  0.00000000e+00,   1.11022302e-16,   0.00000000e+00,
           1.00000000e+00]])

### markdown 单元格还支持 LaTex 语法。例如：$$\int_0^{+\infty} x^2 dx$$